import { Response, Request, NextFunction } from 'express';
import * as boom from '@hapi/boom';
import { Prisma } from '@prisma/client';

type errorORM = typeof Prisma.PrismaClientKnownRequestError;
//Middleware that handles errors generated by the boom library.
export function boomErrorHandler(
  err: boom.Boom<any>,
  req: Request,
  res: Response,
  next: NextFunction
) {
  if (err.isBoom) {
    const { output } = err;
    res.status(output.statusCode).json(output.payload);
  }
  next(err);
}

//Middleware that handles errors generated by Prisma.
export function ormErrorHandler(
  err,
  req: Request,
  res: Response,
  next: NextFunction
) {
  if (err instanceof Prisma.PrismaClientKnownRequestError) {
    if (err.code === 'P2002') {
      res.status(409).json({
        statusCode: 409,
        error: 'Conflict',
        message: 'Email already registered, please login.',
      });
    } else res.json(err);
  }
}
//Middleware that handles errors and sends a response with the error message.
export function errorHandler(
  err,
  req: Request,
  res: Response,
  next: NextFunction
) {
  res.status(err.statusCode || 500).json({ message: err });
  next();
}
